/*
 * This source file was generated by the Gradle 'init' task
 */
package com.padlocks;

public class App {
    public static void main(String[] args) {
        WeatherForecastApiClient client = new WeatherForecastApiClient("https://api.weather.gov/gridpoints/STO/53,76/forecast");
        System.out.println(client.getWeatherForecast());
    }
}
